name: release

on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p dist
      - run: zip -r dist/boilerplate.zip .devcontainer .startup.sh
      - uses: softprops/action-gh-release@v2
        id: release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.zip
